name: main CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5 # Checking out the repo
    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install --dev
    - name: Run tests
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run nose2 -v
    - name: Run the script
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run python freitagsfoo.py
