name: main CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install pipenv
      run: python -m pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev --python 3.12
    - name: Run tests
      run: pipenv run nose2 -v
    - name: Run the script
      run: pipenv run python freitagsfoo.py
